services:
  ml_preprocessing:
    build:
      context: .
      dockerfile: Dockerfile.preprocessing
    volumes:
      - ./data:/app/data
    networks:
      - backend

  ml_training:
    build:
      context: .
      dockerfile: Dockerfile.training
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - backend
    depends_on:
      - ml_preprocessing

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - frontend
    depends_on:
      - ml_training

networks:
  frontend:
  backend:
