FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY streamlit_front.py .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_front.py", "--server.address", "0.0.0.0"]